on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
name: 🚀 Deploy website on push
jobs:
  web-deploy:
    name: 🎉 Deploy API
    runs-on: ubuntu-latest
    steps:
    - name: 🚚 Get latest code - Pegando último código
      uses: actions/checkout@v2
    - name: 📂 Sync files - Sincronizando arquivos
      uses: SamKirkland/FTP-Deploy-Action@4.3.2
      with:
        server: ${{ FTP_HOST.FTP_HOST }}
        username: ${{ FTP_HOST.FTP_USER }}
        password: ${{ FTP_HOST.FTP_USER_PASSWORD }}
        exclude: |
          **/.git*
          **/.git*/*
          **/.environment*
